[xdebug]
xdebug.idekey = "PHPSTORM"
xdebug.mode = debug
xdebug.start_with_request = trigger
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.connect_timeout_ms = 1000

file_uploads = On
upload_max_filesize = 5M
post_max_size = 55M
max_file_uploads = 10

[xhprof]
xhprof.output_dir = /var/www/html/xhprof/runs_data
xhprof.collect_additional_info = 1
