[unix_http_server]
file=/var/run/supervisor/supervisor.sock
chmod=0700
chown=www-data:www-data
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[supervisord]
nodaemon=false
childlogdir=/var/log/supervisor
logfile_maxbytes=100MB
logfile_backups=3
loglevel=info
pidfile=/var/run/supervisor/supervisord.pid
logfile=/var/log/supervisor/supervisord.log
user=www-data

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.sock
username=%(ENV_SUPERVISOR_USERNAME)s
password=%(ENV_SUPERVISOR_PASSWORD)s

[include]
files=/etc/supervisor/conf.d/*.conf