# Requires a password to access Redis
requirepass "xV0jW2&cH9+ml1#ngO7-"

protected-mode yes
loglevel debug
logfile "/var/log/redis.log"
databases 1

# Persistence: AOF (Append Only File)
appendonly yes

# Persistence: RDB snapshot (every 60 sec if 1000+ changes)
save 60 1000

# ACL (Access Control Lists)
# Create user "my_user" with password "my_user_password".
user "xX2ynN7vmD" on >"eO5ka3%qgH1@zvXnyG4&" ~* &* +@all